### ISSUE TITLE
NanoBreathControllerUSBDriver link is broken.

### ISSUE THREAD

**Issue by nonsuchpro** [A-KRY/NanoBreathControllerFirmware#1]
NanoBreathControllerUSBDriver link is broken. 404 error.

**Comment by A-KRY** [comment]
Sorry, I forgot to change it to public and now I've fixed it. I'll write a README tomorrow as soon as possible (in UTC 8 time). In fact, I didn't expect anyone to find my project🤣.

**Comment by nonsuchpro** [comment]
> Sorry, I forgot to change it to public and now I've fixed it. I'll write a README tomorrow as soon as possible (in UTC 8 time). In fact, I didn't expect anyone to find my project🤣.

All good. I just wanted to bring it to your attention. I found your project doing my normal search term which is "Arduino MIDI". Your project popped up and I was intrigued. I have a DX7 with the BC-1 Breath Controller but, making your own sounds fun. Cheers!
